name: "Generate TODO Summary"

permissions:
  pull-requests: write
  contents: read

description: "Scans the repository for TODO[tag]: comments and generates a markdown summary."
inputs:
  root_dir:
    description: "Root directory to scan (optional)"
    required: false
    default: ""
  blacklist:
    description: "Blacklist pattern (optional)"
    required: false
    default: ""
  whitelist:
    description: "Whitelist pattern (optional)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
    - name: Checkout action repoAdd commentMore actions
      uses: actions/checkout@v4
      with:
        repository: kao-fu/todo_collect
        ref: main
        path: ./.action-tmp
    - name: Run TODO summary generator
      id: todo-summary
      run: |
        go run ./.action-tmp/main.go \
          ${{ inputs.root_dir && format('--root {0}', inputs.root_dir) || '' }} \
          ${{ inputs.blacklist && format('--blacklist {0}', inputs.blacklist) || '' }} \
          ${{ inputs.whitelist && format('--whitelist {0}', inputs.whitelist) || '' }} \
          > todo_summary.txt
      shell: bash
    - name: Comment TODO summary on PR
      if: github.event_name == 'pull_request'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat todo_summary.txt)"
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      shell: bash
outputs:
  summary:
    description: "The generated TODO summary markdown file."
branding:
  icon: "check-square"
  color: "yellow"
