name: "Generate TODO Summary"

permissions:
  pull-requests: write
  contents: read

description: "Scans the repository for TODO[tag]: comments and generates a markdown summary."
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
    - name: Checkout action repo
      uses: actions/checkout@v4
      with:
        repository: kao-fu/todo_collect
        ref: main
        path: ./
    - name: Run TODO summary generator
      id: todo-summary
      run: |
        bash ./entrypoint.sh > todo_summary.txt
      shell: bash
    - name: Comment TODO summary on PR
      if: github.event_name == 'pull_request'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat todo_summary.txt)"
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      shell: bash
outputs:
  summary:
    description: "The generated TODO summary markdown file."
branding:
  icon: "check-square"
  color: "yellow"
